/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedFerramentasRouteImport } from './routes/_authenticated/ferramentas'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFerramentasRoute =
  AuthenticatedFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/conta': typeof AuthenticatedContaRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/conta': typeof AuthenticatedContaRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/ferramentas': typeof AuthenticatedFerramentasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assinatura'
    | '/biblioteca'
    | '/conta'
    | '/ferramentas'
    | '/painel'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assinatura'
    | '/biblioteca'
    | '/conta'
    | '/ferramentas'
    | '/painel'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/assinatura'
    | '/_authenticated/biblioteca'
    | '/_authenticated/conta'
    | '/_authenticated/ferramentas'
    | '/_authenticated/painel'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ferramentas': {
      id: '/_authenticated/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthenticatedFerramentasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedFerramentasRoute: typeof AuthenticatedFerramentasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedFerramentasRoute: AuthenticatedFerramentasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
